name: Test

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -r requirements.txt -r requirements-dev.txt
      - shell: powershell
        run: .\tests\install.tests.ps1
      - run: python -m pytest
